import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Copy ONNX Runtime WASM files to plugin directory so the web backend can find them
const wasmFiles = [
	"ort-wasm-simd-threaded.wasm",
	"ort-wasm-simd-threaded.jsep.wasm",
];
const wasmSrcDir = resolve(__dirname, "node_modules/onnxruntime-web/dist");
for (const file of wasmFiles) {
	const src = resolve(wasmSrcDir, file);
	if (existsSync(src)) {
		copyFileSync(src, resolve(__dirname, file));
	}
}

// Plugin to stub out onnxruntime-node completely.
// onnx.js imports both onnxruntime-node and onnxruntime-web.
// We stub the node build so it doesn't interfere.
const stubOnnxruntimeNode = {
	name: "stub-onnxruntime-node",
	setup(build) {
		build.onResolve({ filter: /^onnxruntime-node$/ }, () => ({
			path: "onnxruntime-node",
			namespace: "stub-onnxruntime-node",
		}));
		build.onLoad({ filter: /.*/, namespace: "stub-onnxruntime-node" }, () => ({
			contents: "module.exports = {};",
			loader: "js",
		}));
	},
};
// Plugin to force onnxruntime-web to use its BROWSER build AND patch
// dynamic imports that Electron blocks.
//
// Problem chain:
// 1. esbuild CJS format → onnxruntime-web resolves to ort.node.min.js
//    → registers globalThis[Symbol.for('onnxruntime')]
//    → @huggingface/transformers skips web code path → supportedDevices=[]
// 2. Even with browser build (ort.wasm.bundle.min.mjs), onnxruntime-web
//    uses dynamic import() to load ort-wasm-simd-threaded.mjs at runtime.
//    Electron blocks file:// dynamic imports → "Failed to fetch" error.
//
// Solution: Read the source file, replace dynamic import() with require()
// so esbuild can bundle it at build time. No runtime file:// loads needed.
const forceOnnxWebBrowser = {
	name: "force-onnxruntime-web-browser",
	setup(build) {
		const ortWebDist = resolve(__dirname, "node_modules/onnxruntime-web/dist");

		// Resolve bare import to the WASM-only bundle (no WebGPU/WebGL JSEP)
		build.onResolve({ filter: /^onnxruntime-web$/ }, () => ({
			path: resolve(ortWebDist, "ort.wasm.bundle.min.mjs"),
		}));

		// Intercept loading of the bundle file to patch dynamic imports
		build.onLoad({ filter: /ort\.wasm\.bundle\.min\.mjs$/ }, async (args) => {
			const { readFileSync } = await import('node:fs');
			let code = readFileSync(args.path, 'utf8');

			const wasmModulePath = resolve(ortWebDist, "ort-wasm-simd-threaded.mjs");

			// Prepend a STATIC require() that esbuild can follow and bundle.
			// Then make the dynamic import function (Mn) just return this
			// pre-loaded module instead of doing a runtime import().
			const preload = `var __ort_wasm_threaded__ = require(${JSON.stringify(wasmModulePath)});\n`;

			// Replace: Mn=async e=>(await import(/*webpackIgnore:true*/e)).default
			// With:   Mn=async e=>__ort_wasm_threaded__
			// The module's default export IS the factory function.
			code = code.replace(
				/Mn=async\s+e=>\(await import\(\/\*webpackIgnore:true\*\/e\)\)\.default/,
				`Mn=async e=>(__ort_wasm_threaded__.__esModule?__ort_wasm_threaded__.default:__ort_wasm_threaded__)`
			);

			return { contents: preload + code, loader: 'js', resolveDir: ortWebDist };
		});

		// Patch ort-wasm-simd-threaded.mjs: remove import.meta.url (unavailable
		// in CJS output) and worker_threads import (unneeded in Electron renderer)
		build.onLoad({ filter: /ort-wasm-simd-threaded\.mjs$/ }, async (args) => {
			const { readFileSync } = await import('node:fs');
			let code = readFileSync(args.path, 'utf8');

			// Replace import.meta.url with a valid dummy URL.
			// Emscripten uses new URL("file.wasm", import.meta.url) to locate
			// assets - undefined causes "Invalid URL". Using a dummy URL prevents
			// the crash; the URL is never fetched since we provide wasmBinary.
			code = code.replace(/import\.meta\.url/g, '"https://localhost/"');

			// Remove the worker_threads dynamic import and pthread check at the end
			// (not needed in Electron's renderer where we run single-threaded)
			code = code.replace(
				/var isNode.*isPthread\s*&&\s*ortWasmThreaded\(\);?/s,
				'/* worker_threads check removed for Electron */'
			);

			return { contents: code, loader: 'js', resolveDir: ortWebDist };
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [stubOnnxruntimeNode, forceOnnxWebBrowser],
	conditions: ["browser"],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"sharp",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	define: {
		"import.meta.url": "undefined",
		// Force Transformers.js to use onnxruntime-web (browser path) instead of
		// onnxruntime-node (native bindings that fail when bundled).
		// The check is: process?.release?.name === 'node' → IS_NODE_ENV
		"process.release.name": "undefined",
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
